stages:
  - stage: Continuous Integration
    displayName: CI
    jobs:
      - job: buildjob
        displayName: build
        steps:
          - script: dotnet restore
            displayName: restore
          - script: dotnet build
            displayName: build